name: CI/CD for Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the main branch

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud SDK
      - name: Install and configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

            
      # Create Artifact Registry repository if it doesn't exist
      - name: Create Artifact Registry repository if it doesn't exist
        run: |
          REPO_NAME=koinx-assignment
          REGION=asia-south1
          # Check if the repository exists
          REPO_EXISTS=$(gcloud artifacts repositories list --filter="name:$REPO_NAME" --format="value(name)")
          if [ -z "$REPO_EXISTS" ]; then
            echo "Repository does not exist, creating it now..."
            gcloud artifacts repositories create $REPO_NAME --repository-format=docker --location=$REGION
          else
            echo "Repository already exists."
          fi

      # Configure Docker for Artifact Registry authentication
      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker

      # Authenticate with Google Cloud
      # - name: Authenticate with Google Cloud
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      #   run: |
      #     echo ${{ secrets.GCP_SA_KEY }} > $HOME/gcloud-key.json
      #     gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
      #     gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}:$GITHUB_SHA .

      # Push Docker image to Google Container Registry
      - name: Push Docker image to GCR
        run: |
          docker push ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}:$GITHUB_SHA

      # Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-app \
            --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}:$GITHUB_SHA \
            --platform managed \
            --region ${REGION} \
            --allow-unauthenticated
