name: CI/CD for Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the main branch

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # ✅ Set Google Cloud project and region
      - name: Set GCloud config
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.REGION }}

      # ✅ Create Artifact Registry repository if it doesn't exist
      - name: Create Artifact Registry repository if it doesn't exist
        run: |
          REPO_NAME=${{ secrets.REPO_NAME }}
          REGION=${{ secrets.REGION }}
          # Check if the repository exists
          REPO_EXISTS=$(gcloud artifacts repositories list --filter="repositoryId=$REPO_NAME" --format="value(name)")
          if [ -z "$REPO_EXISTS" ]; then
            echo "Repository does not exist, creating it now..."
            gcloud artifacts repositories create $REPO_NAME --repository-format=docker --location=$REGION
          else
            echo "Repository already exists."
          fi


      # ✅ Configure Docker for Artifact Registry authentication
      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud artifacts repositories configure-docker \
          --location=${{ secrets.REGION }} \
          ${REGION}-docker.pkg.dev

      # ✅ Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}:$GITHUB_SHA .

      # ✅ Push Docker image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}:$GITHUB_SHA

      # ✅ Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-app \
            --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPO_NAME}:$GITHUB_SHA \
            --platform managed \
            --region ${REGION} \
            --allow-unauthenticated
